name: rl_bootcamp
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - scipy=1.11.2
  - scikit-learn=1.3.0
  - jupyter=1.0.0
  - notebook=6.5.5
  - ipywidgets=8.0.7
  - pip=23.1.2
  - pip:
    - gym==0.26.2
    - gymnasium==0.29.0
    - stable-baselines3==2.1.0
    - torch==2.0.1
    - tensorboard==2.13.0
    - tensorflow==2.13.0
    - keras==2.13.1
    - seaborn==0.12.2
    - plotly==5.16.0
    - pettingzoo==1.23.1
    - tqdm==4.66.1
    - pillow==10.0.0 